Cloud hosted README adjustments
OpenLiberty/guide-microprofile-rest-client-async pull request #110
Opened 2021-03-19 20:00 UTC by AustinSeto

Small formatting fix

2021-03-19 22:08 UTC, gkwan-ibm requested changes
@AustinSeto would you also fix the following:
- **Building and running the application**
  - [x] after startContainer, the text "... localhost:9080/query/systemLoad..." -> " http:localhost:9080/query/systemLoad..." 
  - [x] change the "The services take some time..." to "The services may take several minutes to become available." for cloud-hosted guide only
- **Testing the query microservice** 
  - [ ] add an extra statement to tell users "Tests may take several minutes to complete."

2021-03-22 16:16 UTC, dmuelle reviewed
a few suggestions

2021-03-22 16:16 UTC, dmuelle commented on README.adoc
> +You can access the application by making requests to the `query/systemLoad` endpoint by going to http://localhost:9080/query/systemLoad[http://localhost:9080/query/systemLoad^].
You can access the application by making requests to the `query/systemLoad` endpoint by going to the http://localhost:9080/query/systemLoad[http://localhost:9080/query/systemLoad^] URL.

2021-03-22 16:16 UTC, dmuelle commented on README.adoc
>  You'll update the template interface for a MicroProfile Rest Client, which maps to the remote service that you want to call, to use the `CompletionStage` return type.
suggested edit:

You'll update the template interface for a MicroProfile Rest Client to use the `CompletionStage` return type. 

The template interface maps to the remote service that you want to call.

2021-03-22 17:11 UTC, AustinSeto commented
Thank you @dmuelle, all suggestions implemented

2021-03-22 17:36 UTC, dmuelle approved these changes
LGTM

2021-03-22 18:53 UTC, gkwan-ibm approved these changes

2021-03-22 18:56 UTC, merged